pipeline {
    agent any

    environment {
        APP_NAME = 'sync-service'
    }

    stages {

        stage('Checkout') {
            steps {
                git url: 'https://github.com/honeyy02/Assignment-DevOps.git', branch: "${env.BRANCH_NAME}"
                script {
                    env.TARGET_ENV = getTargetEnv(env.BRANCH_NAME)
                }
                echo "Branch: ${env.BRANCH_NAME} → Environment: ${env.TARGET_ENV}"
            }
        }

        stage('Build') {
            agent {
                docker {
                    image 'maven:3.9.9-eclipse-temurin-17'
                }
            }
            steps {
                dir('sync-service-cicd') {
                    sh 'mvn clean package'
                }
            }
        }

        stage('Docker Build') {
            steps {
                dir('sync-service-cicd') {
                    sh 'docker build -t sync-service:local .'
                }
            }
        }

        stage('Approval (Prod)') {
            when {
                branch 'main'
            }
            steps {
                input message: "Deploy to PRODUCTION?"
            }
        }

        stage('Deploy (Local)') {
            when {
                anyOf {
                    branch 'dev'
                    branch 'staging'
                    branch 'main'
                }
            }
            steps {
                 script {
                    def envName = getTargetEnv(env.BRANCH_NAME)
                    echo "Deploying branch ${env.BRANCH_NAME} to ${envName}"
                    dir('sync-service-cicd') {
                        sh "./deploy.sh ${envName}"
                    }
                }
            }
        }
    }
}

def getTargetEnv(branch) {
    switch (branch) {
        case 'dev':     return 'qa'
        case 'staging': return 'staging'
        case 'main':    return 'prod'
        default:        return 'local'
    }
}